config/routes.rb
ArAppy::Application.routes.draw do

  root :to => "apps#index"
  devise_for :users
  resources :users
  resources :apps do
  	collection do
  		post :fetch
      post :top_rank
      get :filter
      get :top
  	end
  end

  get '/settings' => 'stats#settings', :as => :settings

  require 'sidekiq/web'
  mount Sidekiq::Web => '/sidekiq'
end

app/views/apps/filter.html.haml
= render 'shared/subnavigation', :page => :filter
.main
  .main-inner
    .container
      = form_tag filter_apps_path, :method => :get do
        .row
          .span12
            = render 'shared/flash', :flash => flash
          .span6
            .widget
              .widget-header
                %i.icon-check-empty
                %h3 APP TYPE
              .widget-content
                .row
                  .span3
                    = check_box_tag 'type[ipad]', true, (params[:type][:ipad] ? {:checked => true} : nil rescue nil)
                    = label :type, :ipad, 'iPad'
                  .span3
                    = check_box_tag 'type[iphone]', true, (params[:type][:iphone] ? {:checked => true} : nil rescue nil)
                    = label :type, :iphone, 'iPhone'
            .widget
              .widget-header
                %i.icon-tasks
                %h3 CATEGORY
              .widget-content
                .row
                  .span3
                    = check_box_tag 'category[free]', true, (params[:category][:free] ? {:checked => true} : nil rescue nil)
                    = label :category, :free, 'Free'
                  .span3
                    = check_box_tag 'category[paid]', true, (params[:category][:paid] ? {:checked => true} : nil rescue nil)
                    = label :category, :paid, 'Paid'
                  .span3
                    = check_box_tag 'category[grossing]', true, (params[:category][:grossing] ? {:checked => true} : nil rescue nil)
                    = label :category, :grossing, 'Grossing'
          .span6
            .widget
              .widget-header
                %i.icon-flag
                %h3 COUNTRY
              .widget-content
                - @markets.each_slice(2) do |m1, m2|
                  .row
                    - if m1
                      .span3
                        = check_box_tag "market[#{m1.iso}]", true, (params[:market][m1.iso] ? {:checked => true} : nil rescue nil)
                        = label :market, m1.iso, m1.iso.upcase
                    - if m2
                      .span3
                        = check_box_tag "market[#{m2.iso}]", true, (params[:market][m2.iso] ? {:checked => true} : nil rescue nil)
                        = label :market, m2.iso, m2.iso.upcase
        .row
          .span4.offset4
            %p
              %button.btn.btn-large.wide-apply
                %i.icon-share
                Apply

      - if @apps.any?
        .row
          .span12
            .widget.widget-table.action-table
              .widget-header
                %i.icon-th-list
                %h3 Apps
              .widget-content
                %table.table.table-striped.table-bordered.apps
                  %thead
                    %tr
                      %th App Name
                      %th Markets
                      %th Categories
                      %th.td-actions
                  %tbody
                    - @apps.each do |app|
                      %tr
                        %td.wide= link_to app.name, app.link, :target => '_blank'
                        %td.normal
                          - app.markets.collect(&:iso).each do |market|
                            %span.badge.market.pull-left
                              = market.upcase
                        %td.wide
                          - app.market_categories.collect.each do |market_category|
                            %span.label.market.pull-left{:rel => "tooltip", :'data-title' => app.rank_at(market_category).try(:position)}
                              = "#{market_category.market.iso}_#{market_category.category.symbol}"
                          .clearfix
                        %td.td-actions
                          %a.btn.btn-small{:href => app_path(app.id), 'data-method' => :delete, 'data-confirm' => "Are you sure you want to delete this app?"}
                            %i.btn-icon-only.icon-remove
            = paginate @apps

= render 'shared/extrabar'

app/views/apps/index.html.haml
= render 'shared/subnavigation', :page => :home
.main
  .main-inner
    .container
      .row
        .span12
          = render 'shared/flash', :flash => flash
      .row
        .span3
          .widget
            .widget-header
              %i.icon-star
              %h3 Quick Stats
            .widget-content
              .stats
                .stat
                  %span.stat-value
                    = @apps.count
                  Arabic Apps
        .span9
          .widget.widget-table.action-table
            .widget-header
              %i.icon-th-list
              %h3 Apps
            .widget-content
              %table.table.table-striped.table-bordered.apps
                %thead
                  %tr
                    %th App Name
                    %th Markets
                    %th Categories
                    %th.td-actions
                %tbody
                  - @apps.each do |app|
                    %tr
                      %td.wide= link_to app.name, app.link, :target => '_blank'
                      %td.normal
                        - app.markets.collect(&:iso).each do |market|
                          %span.badge.market.pull-left
                            = market.upcase
                      %td.wide
                        - app.market_categories.each do |market_category|
                          %span.label.market.pull-left{:rel => "tooltip", :'data-title' => app.rank_at(market_category).try(:position)}
                            = "#{market_category.market.iso}_#{market_category.category.symbol}"
                        .clearfix
                      %td.td-actions
                        %a.btn.btn-small{:href => app_path(app.id), 'data-method' => :delete, 'data-confirm' => "Are you sure you want to delete this app?"}
                          %i.btn-icon-only.icon-remove
          = paginate @apps
    //container
  //main-inner
//main
= render 'shared/extrabar'

app/views/apps/top.html.haml
= render 'shared/subnavigation', :page => :top_apps
.main
  .main-inner
    .container
      = form_tag top_apps_path, :method => :get do
        .row
          .span12
            = render 'shared/flash', :flash => flash
        .row
          .span6
            .widget
              .widget-header
                %i.icon-check-empty
                %h3 APP TYPE
              .widget-content
                .row
                  .span3
                    = radio_button_tag 'type', 'ipad', (params[:type] == 'ipad' ? true : nil)
                    = label :type, :ipad, 'iPad'
                  .span3
                    = radio_button_tag 'type', 'iphone', (params[:type] == 'iphone' || params[:type].nil? ? true : nil)
                    = label :type, :iphone, 'iPhone'
            
          .span6
            .widget
              .widget-header
                %i.icon-tasks
                %h3 CATEGORY
              .widget-content
                .row
                  .span3
                    = radio_button_tag 'category', 'free', (params[:category] == 'free' || params[:category].nil? ? true : nil)
                    = label :category, :free, 'Free'
                  .span3
                    = radio_button_tag 'category', 'paid', (params[:category] == 'paid' ? true : nil)
                    = label :category, :paid, 'Paid'
                  .span3
                    = radio_button_tag 'category', 'grossing', (params[:category] == 'grossing' ? true : nil)
                    = label :category, :grossing, 'Grossing'
                
        .row
          .span4.offset4
            %p
              .btn-group
                %button.btn.btn-large{:name => :top, :value => 10, :class => (params[:top] == '10' ? 'btn-success' : nil)} Top 10
                %button.btn.btn-large{:name => :top, :value => 30, :class => (params[:top] == '30' ? 'btn-success' : nil)} Top 30
                %button.btn.btn-large{:name => :top, :value => 50, :class => (params[:top] == '50' ? 'btn-success' : nil)} Top 50

      - if @apps.any?
        .row
          .span12
            .widget.widget-table.action-table
              .widget-header
                %i.icon-th-list
                %h3 Apps
              .widget-content
                %table.table.table-striped.table-bordered.apps
                  %thead
                    %tr
                      %th App Name
                      %th Markets
                      %th Categories
                      %th.td-actions
                  %tbody
                    - @apps.each do |app|
                      %tr
                        %td.wide= link_to app.name, app.link, :target => '_blank'
                        %td.normal
                          - app.markets.collect(&:iso).each do |market|
                            %span.badge.market.pull-left
                              = market.upcase
                        %td.wide
                          - app.market_categories.collect.each do |market_category|
                            %span.label.market.pull-left{:rel => "tooltip", :'data-title' => app.rank_at(market_category).try(:position)}
                              = "#{market_category.market.iso}_#{market_category.category.symbol}"
                          .clearfix
                        %td.td-actions
                          %a.btn.btn-small{:href => app_path(app.id), 'data-method' => :delete, 'data-confirm' => "Are you sure you want to delete this app?"}
                            %i.btn-icon-only.icon-remove
            = paginate @apps

= render 'shared/extrabar'